name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Generate the snake
        uses: Platane/snk@v3.0.0  # Use the latest version
        with:
          github_user_name: samadaman
          outputs: dist/snake.svg

      - name: Commit and push the snake animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Generate snake animation"
          git push

      - name: Upload the snake animation
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: snake
          path: dist/snake.svg
